In [1]:
import numpy as np
import pandas as pd

In [8]:
df=pd.read_excel('employee_contact.xlsx')

In [47]:
df.head()

,Staff Member,Corporate Email,City,Mobile,Role,Department Name_x,Contact Number_x,Current Status_x,Employee Code_x,Department Name_y,Contact Number_y,Current Status_y,Employee Code_y,Department Name,Contact Number,Current Status,Employee Code
0,riya thomas,riya.t@company.com,Chennai,NaN,Product Manager,Product,9.876501e+09,Active,EMP112,Product,9.876501e+09,Active,EMP112,Product,9.876501e+09,Active,EMP112
1,Neha Gupta,neha.g@company.com,Noida,NaN,Recruiter,HR,9.876501e+09,Active,EMP108,HR,9.876501e+09,Active,EMP108,HR,9.876501e+09,Active,EMP108
2,Sneha Kapoor,sneha.k@company.com,Mumbai,9.876501e+09,Finance Associate,Finance,9.876501e+09,Active,EMP104,Finance,9.876501e+09,Active,EMP104,Finance,9.876501e+09,Active,EMP104

In [10]:
df2=pd.read_excel('employee_department.xlsx')

In [11]:
df3=pd.read_excel('employee_master.xlsx')

In [12]:
df2.head(2)

      Associate Department Name  Contact Number Current Status Employee Code
0  anjali singh          Design             NaN         Active        EMP106
1   Neha  Gupta              HR    9.876501e+09         Active        EMP108

In [20]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Associate        12 non-null     object
 1   Department Name  12 non-null     object
 2   Contact Number   8 non-null      float64
 3   Current Status   12 non-null     object
 4   Employee Code    12 non-null     object
dtypes: float64(1), object(4)
memory usage: 612.0+ bytes

In [18]:
# df.merge(df2, left_on='Mobile', right_on='Contact Number', how='left')

In [24]:
df.isnull().sum() #we can remove or might be there in other excel sheet

Staff Member       0
Corporate Email    0
City               0
Mobile             6
Role               0
dtype: int64

In [28]:
for col in df.columns:
    print(f"Unique values in {col}: {df[col].nunique()}")   #any of them can be pk

Unique values in Staff Member: 12
Unique values in Corporate Email: 12
Unique values in City: 12
Unique values in Mobile: 6
Unique values in Role: 12

In [29]:
for col in df2.columns:
    print(f"Unique values in {col}: {df2[col].nunique()}")   #any of them can be pk

Unique values in Associate: 12
Unique values in Department Name: 8
Unique values in Contact Number: 8
Unique values in Current Status: 3
Unique values in Employee Code: 12

In [34]:
df2=df2.rename(columns={'Associate':'Staff Member'})

In [48]:
df2.head()

   Staff Member Department Name  Contact Number Current Status Employee Code
0  anjali singh          Design             NaN         Active        EMP106
1   Neha  Gupta              HR    9.876501e+09         Active        EMP108
2   Rahul Verma       Analytics    9.876501e+09       On Leave        EMP103
3    Pooja Jain              IT             NaN         Active        EMP110
4     ARJUN DAS       Analytics    9.876501e+09       Inactive        EMP111

In [49]:
#df=pd.merge(df,df2,on="Staff Member")
#df=df.merge(df2,on="Staff Member")

In [53]:
df = pd.read_excel('employee_contact.xlsx')
df.head()

,Staff Member,Corporate Email,City,Mobile,Role
0,Karan Patel,karan.p@company.com,Ahmedabad,NaN,Marketing Lead
1,Arjun Das,arjun.d@company.com,Kolkata,9.876501e+09,Business Analyst
2,Anjali Singh,anjali.s@company.com,Pune,NaN,UI Designer
3,RAHUL VERMA,rahul.verma@company.com,Delhi,9.876501e+09,Data Analyst
4,riya thomas,riya.t@company.com,Chennai,NaN,Product Manager

In [54]:
df['Staff Member'] = df['Staff Member'].str.lower()
df2['Staff Member'] = df2['Staff Member'].str.lower()

In [55]:
df_merged = df.merge(df2, on='Staff Member', how='left')
df_merged.head()

,Staff Member,Corporate Email,City,Mobile,Role,Department Name,Contact Number,Current Status,Employee Code
0,karan patel,karan.p@company.com,Ahmedabad,NaN,Marketing Lead,NaN,NaN,NaN,NaN
1,arjun das,arjun.d@company.com,Kolkata,9.876501e+09,Business Analyst,Analytics,9.876501e+09,Inactive,EMP111
2,anjali singh,anjali.s@company.com,Pune,NaN,UI Designer,Design,NaN,Active,EMP106
3,rahul verma,rahul.verma@company.com,Delhi,9.876501e+09,Data Analyst,Analytics,9.876501e+09,On Leave,EMP103
4,riya thomas,riya.t@company.com,Chennai,NaN,Product Manager,Product,9.876501e+09,Active,EMP112

In [58]:
df_merged.shape

(12, 9)

In [ ]:
#i can not just remove one of the same column because some of  them ve null some do not
#df_merged.remove(columns={'Mobile	',''})

In [68]:
df_merged["merge_job"] = df_merged["Department Name"].combine_first(df_merged["Role"])

In [69]:
df_merged.sample(5)

,Staff Member,Corporate Email,City,Mobile,Role,Department Name,Contact Number,Current Status,Employee Code,merge_job
8,mohit sharma,mohit.s@company.com,Jaipur,NaN,Sales Manager,NaN,NaN,NaN,NaN,Sales Manager
9,pooja jain,pooja.j@company.com,Indore,9.876501e+09,QA Engineer,IT,NaN,Active,EMP110,IT
0,karan patel,karan.p@company.com,Ahmedabad,NaN,Marketing Lead,NaN,NaN,NaN,NaN,Marketing Lead
7,aarav mehta,aarav.mehta@company.com,Bengaluru,9.876501e+09,Software Engineer,NaN,NaN,NaN,NaN,Software Engineer
11,sneha kapoor,sneha.k@company.com,Mumbai,9.876501e+09,Finance Associate,Finance,9.876501e+09,Active,EMP104,Finance

In [70]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Staff Member     12 non-null     object
 1   Corporate Email  12 non-null     object
 2   City             12 non-null     object
 3   Mobile           6 non-null      float64
 4   Role             12 non-null     object
 5   Department Name  8 non-null      object
 6   Contact Number   6 non-null      float64
 7   Current Status   8 non-null      object
 8   Employee Code    8 non-null      object
 9   merge_job        12 non-null     object
dtypes: float64(2), object(8)
memory usage: 1.1+ KB

In [71]:
df_merged["merged_contact_number"] = df_merged["Mobile"].combine_first(df_merged["Contact Number"])

In [72]:
df_merged.head()

,Staff Member,Corporate Email,City,Mobile,Role,Department Name,Contact Number,Current Status,Employee Code,merge_job,merged_contact_number
0,karan patel,karan.p@company.com,Ahmedabad,NaN,Marketing Lead,NaN,NaN,NaN,NaN,Marketing Lead,NaN
1,arjun das,arjun.d@company.com,Kolkata,9.876501e+09,Business Analyst,Analytics,9.876501e+09,Inactive,EMP111,Analytics,9.876501e+09
2,anjali singh,anjali.s@company.com,Pune,NaN,UI Designer,Design,NaN,Active,EMP106,Design,NaN
3,rahul verma,rahul.verma@company.com,Delhi,9.876501e+09,Data Analyst,Analytics,9.876501e+09,On Leave,EMP103,Analytics,9.876501e+09
4,riya thomas,riya.t@company.com,Chennai,NaN,Product Manager,Product,9.876501e+09,Active,EMP112,Product,9.876501e+09

In [74]:
df_merged.drop(columns=['Mobile','Contact Number','Department Name','Role'], inplace=True)

In [75]:
df_merged.head()

,Staff Member,Corporate Email,City,Current Status,Employee Code,merge_job,merged_contact_number
0,karan patel,karan.p@company.com,Ahmedabad,NaN,NaN,Marketing Lead,NaN
1,arjun das,arjun.d@company.com,Kolkata,Inactive,EMP111,Analytics,9.876501e+09
2,anjali singh,anjali.s@company.com,Pune,Active,EMP106,Design,NaN
3,rahul verma,rahul.verma@company.com,Delhi,On Leave,EMP103,Analytics,9.876501e+09
4,riya thomas,riya.t@company.com,Chennai,Active,EMP112,Product,9.876501e+09

In [76]:
df3.head()

,Employee Full Name,Employee ID,Designation,Office Location,Work Email
0,NEHA GUPTA,EMP108,Recruiter,Noida,neha.g@company.com
1,anjali singh,EMP106,UI Designer,Pune,anjali.s@company.com
2,Rahul Verma,EMP103,Data Analyst,Delhi,rahul.verma@company.com
3,Karan Patel,EMP109,Marketing Lead,Ahmedabad,karan.p@company.com
4,Pooja Jain,EMP110,QA Engineer,Indore,pooja.j@company.com

In [77]:
df3['Employee ID'].nunique()

12

In [79]:
df3=df3.rename(columns={'Employee ID':'Employee Code'})

In [83]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Staff Member           12 non-null     object
 1   Corporate Email        12 non-null     object
 2   City                   12 non-null     object
 3   Current Status         8 non-null      object
 4   Employee Code          8 non-null      object
 5   merge_job              12 non-null     object
 6   merged_contact_number  9 non-null      float64
dtypes: float64(1), object(6)
memory usage: 804.0+ bytes

In [82]:
df_merged_2 = df_merged.merge(df3, on='Employee Code', how='left')
df_merged_2.head()

,Staff Member,Corporate Email,City,Current Status,Employee Code,merge_job,merged_contact_number,Employee Full Name,Designation,Office Location,Work Email
0,karan patel,karan.p@company.com,Ahmedabad,NaN,NaN,Marketing Lead,NaN,NaN,NaN,NaN,NaN
1,arjun das,arjun.d@company.com,Kolkata,Inactive,EMP111,Analytics,9.876501e+09,arjun das,Business Analyst,Kolkata,arjun.d@company.com
2,anjali singh,anjali.s@company.com,Pune,Active,EMP106,Design,NaN,anjali singh,UI Designer,Pune,anjali.s@company.com
3,rahul verma,rahul.verma@company.com,Delhi,On Leave,EMP103,Analytics,9.876501e+09,Rahul Verma,Data Analyst,Delhi,rahul.verma@company.com
4,riya thomas,riya.t@company.com,Chennai,Active,EMP112,Product,9.876501e+09,riya thomas,Product Manager,Chennai,riya.t@company.com

In [84]:
df_merged_2.drop(columns=['Employee Full Name','Designation','Office Location','Work Email'], inplace=True)

In [86]:
df_merged_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Staff Member           12 non-null     object
 1   Corporate Email        12 non-null     object
 2   City                   12 non-null     object
 3   Current Status         8 non-null      object
 4   Employee Code          8 non-null      object
 5   merge_job              12 non-null     object
 6   merged_contact_number  9 non-null      float64
dtypes: float64(1), object(6)
memory usage: 804.0+ bytes

In [87]:
df_merged_2.head()

,Staff Member,Corporate Email,City,Current Status,Employee Code,merge_job,merged_contact_number
0,karan patel,karan.p@company.com,Ahmedabad,NaN,NaN,Marketing Lead,NaN
1,arjun das,arjun.d@company.com,Kolkata,Inactive,EMP111,Analytics,9.876501e+09
2,anjali singh,anjali.s@company.com,Pune,Active,EMP106,Design,NaN
3,rahul verma,rahul.verma@company.com,Delhi,On Leave,EMP103,Analytics,9.876501e+09
4,riya thomas,riya.t@company.com,Chennai,Active,EMP112,Product,9.876501e+09

In [ ]:
#now combine excel sheet is here i can convert it into db or use it normally
#deciision making should i remove all null value columns everything on me
#i can add some constrains
#if employee code is not there remove that person
#contact to 0

In [ ]:
#we can perform EDA to visualize things